package GUISmartFactory;

import com.mycompany.smartfactorymonitoringsystem.AlertServiceGrpc;
import com.mycompany.smartfactorymonitoringsystem.MachineMonitorServiceGrpc;
import com.mycompany.smartfactorymonitoringsystem.MaintenanceScheduleServiceGrpc;
import com.mycompany.smartfactorymonitoringsystem.SmartFactoryProto;
import com.mycompany.smartfactorymonitoringsystem.SmartFactoryProto.LogEntry;
import com.mycompany.smartfactorymonitoringsystem.SmartFactoryProto.LogSummary;
import com.mycompany.smartfactorymonitoringsystem.SmartFactoryProto.MaintenanceResponse;
import com.mycompany.smartfactorymonitoringsystem.SmartFactoryProto.MetricUpdate;
import com.mycompany.smartfactorymonitoringsystem.SmartFactoryProto.MonitorRequest;
import io.grpc.Deadline;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Metadata;
import io.grpc.StatusRuntimeException;
import io.grpc.stub.MetadataUtils;
import io.grpc.stub.StreamObserver;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vcaro
 */
public class GUISmartFactory extends javax.swing.JFrame {
    private ManagedChannel channel;
    private Metadata headers;
    private ManagedChannel channelAlert;
    private ManagedChannel channelMaintenance;
    private StreamObserver<SmartFactoryProto.MaintenanceRequest> requestObserver;





    /**
     * Creates new form GUISmartFactory
     */
    public GUISmartFactory() {
        initComponents();
        channel = ManagedChannelBuilder.forAddress("localhost", 9001)
            .usePlaintext()
            .build();
        
        
        channelAlert = ManagedChannelBuilder.forAddress("localhost", 9002)
            .usePlaintext()
            .build();
        
        channelMaintenance = ManagedChannelBuilder.forAddress("localhost", 9003)
                .usePlaintext()
                .build();

        
        Metadata.Key<String> AUTH_KEY = Metadata.Key.of("authorization", Metadata.ASCII_STRING_MARSHALLER);
        headers = new Metadata();
        headers.put(AUTH_KEY, "my_secret_token");

        MachineMonitorServiceGrpc.MachineMonitorServiceStub asyncStub = MachineMonitorServiceGrpc.newStub(channel)
        .withDeadline(Deadline.after(5, TimeUnit.SECONDS));
        asyncStub = MetadataUtils.attachHeaders(asyncStub, headers);
        
        AlertServiceGrpc.AlertServiceBlockingStub stub2 = AlertServiceGrpc.newBlockingStub(channelAlert)
                                .withDeadline(Deadline.after(3, TimeUnit.SECONDS));
                        stub2 = MetadataUtils.attachHeaders(stub2, headers);
                        
        MaintenanceScheduleServiceGrpc.MaintenanceScheduleServiceStub asyncStub2 = MaintenanceScheduleServiceGrpc
            .newStub(channelMaintenance)
            .withDeadline(Deadline.after(5, TimeUnit.SECONDS));
             asyncStub2 = MetadataUtils.attachHeaders(asyncStub2, headers);
             
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonMachine = new javax.swing.JButton();
        ButtonAlert = new javax.swing.JButton();
        ButtonMaintenance = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnCheckStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResultArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnCheckStatus2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonDiagnostics = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAlert = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButtonStartMain = new javax.swing.JButton();
        jButtonEnd = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMain = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setBackground(new java.awt.Color(153, 204, 255));
        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("    SMART FACTORY MONITORING SYSTEM");
        title.setAutoscrolls(true);
        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        buttonMachine.setBackground(new java.awt.Color(153, 153, 255));
        buttonMachine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonMachine.setText("MACHINE MONITOR");
        buttonMachine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMachineActionPerformed(evt);
            }
        });

        ButtonAlert.setBackground(new java.awt.Color(153, 153, 255));
        ButtonAlert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonAlert.setText("ALERTS");
        ButtonAlert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlertActionPerformed(evt);
            }
        });

        ButtonMaintenance.setBackground(new java.awt.Color(153, 153, 255));
        ButtonMaintenance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonMaintenance.setText("MAINTENANCE");
        ButtonMaintenance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setForeground(new java.awt.Color(153, 0, 0));

        btnCheckStatus.setBackground(new java.awt.Color(102, 102, 255));
        btnCheckStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCheckStatus.setText("Check Status");
        btnCheckStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStatusActionPerformed(evt);
            }
        });

        textResultArea.setColumns(20);
        textResultArea.setRows(5);
        jScrollPane1.setViewportView(textResultArea);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MACHINES");

        jTextField1.setText("Motors: Motor A, Motor B, Motor C");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Monitor Check");

        jTextField2.setText("Temerature, Vibration, Time");

        jSeparator3.setForeground(new java.awt.Color(153, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ALERTS");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnCheckStatus2.setBackground(new java.awt.Color(102, 102, 255));
        btnCheckStatus2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCheckStatus2.setText("Check Status");
        btnCheckStatus2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckStatus2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCheckStatus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStatus2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButtonDiagnostics.setBackground(new java.awt.Color(102, 102, 255));
        jButtonDiagnostics.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDiagnostics.setText("Send Request");
        jButtonDiagnostics.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonDiagnostics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiagnosticsActionPerformed(evt);
            }
        });

        jTextAreaAlert.setColumns(20);
        jTextAreaAlert.setRows(5);
        jScrollPane3.setViewportView(jTextAreaAlert);

        jSeparator4.setForeground(new java.awt.Color(153, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("MAINTENANCE");

        jButtonStartMain.setBackground(new java.awt.Color(102, 102, 255));
        jButtonStartMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonStartMain.setText("Start Maintenance");
        jButtonStartMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartMainActionPerformed(evt);
            }
        });

        jButtonEnd.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEnd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEnd.setText("End Session");
        jButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndActionPerformed(evt);
            }
        });

        jTextAreaMain.setColumns(20);
        jTextAreaMain.setRows(5);
        jScrollPane4.setViewportView(jTextAreaMain);

        jLabel5.setText("Get Diagnostics");

        jLabel6.setText("GetErrors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(buttonMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(ButtonAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonStartMain)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCheckStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(btnCheckStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonDiagnostics, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabel5)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jScrollPane3))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckStatus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCheckStatus2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDiagnostics)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonStartMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnd))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMachineActionPerformed

    private void ButtonAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAlertActionPerformed

    private void btnCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStatusActionPerformed
        // TODO add your handling code here:
    String selectedMachine = jTextField1.toString();

    MachineMonitorServiceGrpc.MachineMonitorServiceStub asyncStub = MachineMonitorServiceGrpc.newStub(channel)
        .withDeadline(Deadline.after(5, TimeUnit.SECONDS));
    asyncStub = MetadataUtils.attachHeaders(asyncStub, headers);

    long currentTimeMillis = System.currentTimeMillis();
    String formattedDate = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
        .format(new java.util.Date(currentTimeMillis));

    MonitorRequest request = MonitorRequest.newBuilder()
        .setMachine(selectedMachine)
        .setTemperature(90)
        .setVibration(100)
        .setTime(currentTimeMillis)
        .build();

    // Clear output
    textResultArea.setText("");

    asyncStub.streamMetrics(request, new StreamObserver<MetricUpdate>() {
        @Override
        public void onNext(MetricUpdate update) {
            String output = "Monitor: " + update.getMachine() +
                "\nTemperature: " + update.getTemperature() +
                "\nVibration: " + update.getVibration() +
                "\nTime: " + formattedDate + "\n\n";

            SwingUtilities.invokeLater(() -> {
                textResultArea.append(output);
            });
        }

        @Override
        public void onError(Throwable t) {
            SwingUtilities.invokeLater(() -> {
                textResultArea.append("Error: " + t.getMessage());
            });
        }

        @Override
        public void onCompleted() {
            SwingUtilities.invokeLater(() -> {
                textResultArea.append("Monitoring completed.\n");
            });
        }
    });


      
    }//GEN-LAST:event_btnCheckStatusActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnCheckStatus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStatus2ActionPerformed
        // TODO add your handling code here:
        
          AlertServiceGrpc.AlertServiceBlockingStub stub2 = AlertServiceGrpc.newBlockingStub(channelAlert)
                                .withDeadline(Deadline.after(3, TimeUnit.SECONDS));
                        stub2 = MetadataUtils.attachHeaders(stub2, headers);

                        try {
                            SmartFactoryProto.AlertResponse resp = stub2.getAlerts(SmartFactoryProto.AlertRequest.newBuilder()
                                    .setAlertType("Alert: Overheating")
                                    .setSeverityLevel("4 (High)")
                                    .build());
                            
                             jTextArea2.setText("Alert Received!\n" +
            "Type: " + resp.getAlertType() + "\n" +
            "Severity: " + resp.getSeverityLevel());

    } catch (StatusRuntimeException e) {
        jTextArea2.setText("Error communicating with server:\n" + e.getStatus());
        System.err.println("Error communicating with server: " + e.getStatus());
    }

    }//GEN-LAST:event_btnCheckStatus2ActionPerformed

    private void jButtonDiagnosticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiagnosticsActionPerformed
        // TODO add your handling code here:
        
        AlertServiceGrpc.AlertServiceStub asyncStub = AlertServiceGrpc.newStub(channelAlert)
            .withDeadline(Deadline.after(5, TimeUnit.SECONDS));

     asyncStub = MetadataUtils.attachHeaders(asyncStub, headers);
// Clear output
    jTextAreaAlert.setText("");

    StreamObserver<LogSummary> responseObserver = new StreamObserver<LogSummary>() {
    @Override
    public void onNext(LogSummary summary) {
        jTextAreaAlert.append(summary.getMessage() + "\n");
    }

    @Override
    public void onError(Throwable t) {
        System.out.println("Error from server: " + t.getMessage());
    }

    @Override
    public void onCompleted() {
        System.out.println("Server finished processing the diagnostics.");
    }
};

StreamObserver<LogEntry> requestObserver = asyncStub.sendDiagnostics(responseObserver);

try {
    requestObserver.onNext(LogEntry.newBuilder()
        .setDiagnostic("Danger of overheating. ")
        .build());

    requestObserver.onNext(LogEntry.newBuilder()
        .setErrors("Overheating in Motor A01 and Motor B02")
        .build());

    Thread.sleep(1000); // Optional delay for dramatic effect
    requestObserver.onCompleted();

} catch (RuntimeException | InterruptedException e) {
    requestObserver.onError(e);
    throw new RuntimeException(e);
}

    }//GEN-LAST:event_jButtonDiagnosticsActionPerformed

    private void jButtonStartMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartMainActionPerformed
        // TODO add your handling code here:
        long currentTimeMillis = System.currentTimeMillis();
                    String formattedDate = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
                   .format(new java.util.Date(currentTimeMillis));
                    
    MaintenanceScheduleServiceGrpc.MaintenanceScheduleServiceStub asyncStub = MaintenanceScheduleServiceGrpc
            .newStub(channelMaintenance)
            .withDeadline(Deadline.after(5, TimeUnit.SECONDS));
    asyncStub = MetadataUtils.attachHeaders(asyncStub, headers);

    // Clear previous output
    jTextAreaMain.setText("");

    // Define response observer
    StreamObserver<SmartFactoryProto.MaintenanceResponse> responseObserver;
        responseObserver = new StreamObserver<SmartFactoryProto.MaintenanceResponse>() {
            
            @Override
            public void onNext(SmartFactoryProto.MaintenanceResponse response) {
                try {
                    // Now include it in your output
                    String output = String.format(
                            "Maintenance Received:\n" +
                                    "Machine ID: %s\n" +
                                    "Date: %s\n" +
                                    "Description: %s\n" +
                                    "Status: %s\n" +
                                    "Technician: %s\n\n",
                            response.getMachineID(),
                            formattedDate,
                            response.getDescription(),
                            response.getStatus(),
                            response.getTechnician()
                    );
                    
                    jTextAreaMain.append(output);
                    
                } catch (Exception e) {
                    jTextAreaMain.append("Failed to format date: " + e.getMessage() + "\n");
                }
            }
            
            @Override
            public void onError(Throwable t) {
                jTextAreaMain.append("Error: " + t.getMessage() + "\n");
            }
            
            @Override
            public void onCompleted() {
                jTextAreaMain.append("Server has finished sending responses.\n");
            }
        };

    // Define request observer
    requestObserver = asyncStub.scheduleMaintenance(responseObserver);

    try {
       SmartFactoryProto.MaintenanceRequest req1 = SmartFactoryProto.MaintenanceRequest.newBuilder()
        .setMachineID("MA01")
        .setDate(currentTimeMillis)
        .setDescription("Schedule inspections due to high levels of vibration")
        .setStatus("Orange: medium danger")
        .setTechnician("John Doe")
        .build();

SmartFactoryProto.MaintenanceRequest req2 = SmartFactoryProto.MaintenanceRequest.newBuilder()
        .setMachineID("MA02")
        .setDate(currentTimeMillis) // use formattedDate here too
        .setDescription("Schedule inspections due to high levels of temperature")
        .setStatus("Red: high danger")
        .setTechnician("Thomas Clarke")
        .build();

SmartFactoryProto.MaintenanceRequest req3 = SmartFactoryProto.MaintenanceRequest.newBuilder()
        .setMachineID("MA20")
        .setDate(currentTimeMillis) // use formattedDate here too
        .setDescription("Schedule inspections does not show errors")
        .setStatus("White: perfect conditions")
        .setTechnician("John Connolly")
        .build();

                            
        // Send requests
        requestObserver.onNext(req1);
        requestObserver.onNext(req2);
        requestObserver.onNext(req3);

    } catch (RuntimeException e) {
        requestObserver.onError(e);
        throw e;
    }
    }//GEN-LAST:event_jButtonStartMainActionPerformed

    private void jButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndActionPerformed
        // TODO add your handling code here:
        if (requestObserver != null) {
        requestObserver.onCompleted();
    }

    }//GEN-LAST:event_jButtonEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISmartFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISmartFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISmartFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISmartFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISmartFactory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlert;
    private javax.swing.JButton ButtonMaintenance;
    private javax.swing.JButton btnCheckStatus;
    private javax.swing.JButton btnCheckStatus2;
    private javax.swing.JButton buttonMachine;
    private javax.swing.JButton jButtonDiagnostics;
    private javax.swing.JButton jButtonEnd;
    private javax.swing.JButton jButtonStartMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaAlert;
    private javax.swing.JTextArea jTextAreaMain;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea textResultArea;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
